# Makefile

# Variables
PYTHON = python3
DATAGEN = dataGen.py
TRYSTUFF = tryStuff.py

# Default target
data:
	$(PYTHON) $(DATAGEN)

run: 
	$(PYTHON) $(TRYSTUFF)

# Clean up __pycache__ and *.pyc files
# clean:
# 	rm -rf __pycache__ *.pyc

# Run tests (assuming you have a test file like test_main.py)
# test:
# 	$(PYTHON) -m unittest test_main.py
